[infra]
rocky-infra-01 ansible_host=192.168.56.10 ansible_user=root

[k8s_nodes]
k8s-master-01 ansible_host=192.168.56.11 ansible_user=user node_management_ip=192.168.56.11/24 node_internal_ip=172.20.0.21
k8s-worker-01 ansible_host=192.168.56.12 ansible_user=user node_management_ip=192.168.56.12/24 node_internal_ip=172.20.0.22

[k8s_control_plane]
k8s-master-01

[k8s_workers]
k8s-worker-01
